export {
  HX, //筛选级联菜单menu
}
const HX = {
  menus: [
    {
      name:'地区',
      type:'li',
      data:[]
    },
    {
      name:'品牌',
      type:'li',
      data:[]
    },
    {
      name:'价格',
      type:'li',
      data:[]
    },
    {
      name:'车龄',
      type:'li',
      data:[]
    },
    {
      name:'公里数',
      type:'',
      data:[]
    },
    {
      name:'类型',
      type:'1',
      data:[
        {name:'不限',val:''},
        {name:'轿车',val:'1'},
        {name:'SUV',val:'7'},
        {name:'跑车',val:'8'},
        {name:'MPV',val:'371'},
        {name:'客车',val:'2'},
        {name:'面包车',val:'10'},
        {name:'皮卡',val:'4'},
        {name:'房车',val:'11'},
        {name:'货车',val:'3'},
        {name:'工程车',val:'6'}
      ]
    },
    {
      name:'级别',
      type:'1',
      data: [
        {name:'不限',val:''},
        {name:'微型',val:'365'},
        {name:'小型',val:'366'},
        {name:'紧凑型',val:'367'},
        {name:'中型',val:'368'},
        {name:'中大型',val:'369'},
        {name:'豪华型',val:'370'}
      ],
    },
    {
      name:'结构',
      type:'1',
      data:[
        {name:'不限',val:''},
        {name:'两厢',val:'两厢'},
        {name:'三厢',val:'三厢'},
        {name:'掀背',val:'掀背'},
        {name:'旅行版',val:'旅行版'},
        {name:'硬顶敞篷',val:'硬顶敞篷'},
        {name:'软顶敞篷',val:'软顶敞篷'}
      ],
    },
    {
      name:'厂商',
      type:'1',
      data:[
        {name:'不限',val:''},
        {name:'自主',val:'自主'},
        {name:'合资',val:'合资'},
        {name:'进口',val:'进口'},
        {name:'美规版',val:'美规版'},
        {name:'中东版',val:'中东版'},
        {name:'欧洲版',val:'欧洲版'}
      ],
    },
    {
      name:'排放',
      type:'1',
      data:[
        {'name':'不限','val':''},
        {'name':'国一','val':'1'},
        {'name':'国二','val':'2'},
        {'name':'国三','val':'3'},
        {'name':'国三ODB','val':'4'},
        {'name':'国四','val':'5'},
        {'name':'国五','val':'6'}
      ],
    },
    {
      name:'变速箱',
      type:'1',
      data:[
        {'name':'不限','val':''},
        {'name':'手动','val':'2'},
        {'name':'自动','val':'1'},
        {'name':'手自一体','val':'3'}
      ],
    },
    {
      name:'国别',
      type:'1',
      data:[
        {'name':'不限',val:''},
        {'name':'中国',val:'348'},
        {'name':'德国',val:'349'},
        {'name':'日本',val:'350'},
        {'name':'韩国',val:'352'},
        {'name':'美国',val:'351'},
        {'name':'英国',val:'354'},
        {'name':'法国',val:'353'},
        {'name':'意大利',val:'355'},
        {'name':'瑞典',val:'357'},
        {'name':'其他',val:''}
      ],
    },
    {
      name:'颜色',
      type:'1',
      data:[
        {'name':'不限','val':''},
        {'name':'黑色','val':'1'},
        {'name':'白色','val':'4'},
        {'name':'银灰','val':'7'},
        {'name':'深灰','val':'8'},
        {'name':'蓝色','val':'3'},
        {'name':'绿色','val':'5'},
        {'name':'香槟','val':'11'},
        {'name':'黄色','val':'6'},
        {'name':'红色',val:'2'}
      ],
    },
    {
      name:'库存时间',
      type:'1',
      data:{}
    },
    {
      name:'批发车源',
      type:'1',
      data:[
        {'name':'不限','val':''},
        {'name':'批发车源','val':'1'}
        ]
    },
  ],
};
